name: check-onshape-version

# Run daily
on:
  schedule:
  - cron: "0 0 * * *"
  push:
    branches: [master]
    
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Get current build of Onshape
        id: onshape-build
        uses: senmu/download-json-property-action@v1.0.0
        with:
          url: 'https://cad.onshape.com/api/build'
          property_path: 'Implementation-Version'
      - name: What is it
        run: echo "${{ steps.onshape-build.outputs.value }}"
      - name: Parse version
        id: parse-version
        uses: actions-ecosystem/action-regex-match@v2
        with:
          text: ${{ steps.onshape-build.outputs.value }}
          regex: '^v?([0-9]+)\.([0-9]+)\.[0-9]+\.[a-z0-9]+$'
      - name: Get Java Client version
        id: java-client
        uses: pozetroninc/github-action-get-latest-release@master
        with:
            repository: onshape-public/java-client
      - name: Parse release
        id: parse-release
        uses: actions-ecosystem/action-regex-match@v2
        with:
          text: ${{ steps.java-client.outputs.value }}
          regex: '^v?([0-9]+)\.([0-9]+)\.[0-9]+\.[a-z0-9]+$'
      - name: Spit it out
        run: echo "Onshape build ${{ steps.parse-semver.outputs.group1}}.${{ steps.parse-semver.outputs.group2}}, Java release ${{ steps.parse-release.outputs.group1}}.${{ steps.parse-release.outputs.group2}}"
        
