name: check-onshape-version

# Run daily
on:
  schedule:
  - cron: "0 0 * * *"
  push:
    branches: [master]
    
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Get current build of Onshape
        id: onshape-build
        uses: senmu/download-json-property-action@v1.0.0
        with:
          url: 'https://cad.onshape.com/api/build'
          property_path: 'Implementation-Version'
      - name: What is it
        run: echo "${{ steps.onshape-build.outputs.value }}"
      - name: Parse version
        id: parse-version
        uses: actions-ecosystem/action-regex-match@v2
        with:
          text: ${{ steps.onshape-build.outputs.value }}
          regex: '^v?([0-9]+)\.([0-9]+)\.[0-9]+\.[a-z0-9]+$'
      - name: Get Java Client version
        id: java-client
        uses: fjogeleit/http-request-action@v1.3.3
        with:
            url: 'https://api.github.com/repos/onshape-public/java-client/tags'
            method: GET
            customHeaders: '{"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36"}'
      - name: Extract latest tag
        id: extract-tag
        uses: ashley-taylor/read-json-property-action@v1.0
        with:
         json: ${{ steps.java-client.outputs.response }}
         property: '0.name'
      - name: Parse release
        id: parse-release
        uses: actions-ecosystem/action-regex-match@v2
        with:
          text: ${{ steps.extract-tag.outputs.value }}
          regex: '^v?([0-9]+)\.([0-9]+)\.[0-9]+\.[a-z0-9]+$'
      - name: Spit it out
        run: echo "Onshape build ${{ steps.parse-version.outputs.group1}}.${{ steps.parse-version.outputs.group2}}, Java client ${{ steps.parse-release.outputs.group1}}.${{ steps.parse-release.outputs.group2}}"
        
